name: vegan_reviews
description: A review app of vegan food for Jody
publish_to: 'none'
version: 1.2.1+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_core: 1.3.0
  cloud_firestore: 2.2.2
  firebase_auth: 1.4.1
  firebase_storage: 8.1.3
  google_sign_in: 5.0.4
  bloc: 7.0.0
  flutter_bloc: 7.0.0
  equatable: 2.0.3
  image_picker: 0.8.0+4
  uuid: 3.0.4
  connectivity: 3.0.6
  intl: 0.17.0
  shared_preferences: 2.0.6

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/plant.png"